-- Add up migration script here
CREATE TABLE IF NOT EXISTS pets (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(40) NOT NULL,
    PERSON_ID VARCHAR(36) REFERENCES people,
    CREATED_ON TIMESTAMP NOT NULL DEFAULT NOW()
);